version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: node-app-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: node-app-db
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - '3000:80'
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/node-app-db
