version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: node-app-db
    ports:
      - '5432:5432'
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB

  ui:
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - '3000:80'
    env_file: .env

    stdin_open: true
